# Generated by Django 4.2.8 on 2024-01-13 12:54

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=200, verbose_name='Məqalə başlığı')),
                ('kontent', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Məqalə kontenti')),
                ('yaradilma_tarixi', models.DateTimeField(verbose_name='Yaranma tarixi')),
                ('deyisdirilme_tarixi', models.DateTimeField(verbose_name='Yaranma tarixi')),
            ],
            options={
                'verbose_name': 'Məqalə',
                'verbose_name_plural': 'Məqalələr',
            },
        ),
    ]
