# Generated by Django 4.2.8 on 2024-01-14 16:11

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basliq', models.CharField(max_length=200, verbose_name='Məqalə başlığı')),
                ('kontent', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Məqalə kontenti')),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('deyisdirilme_tarixi', models.DateTimeField(auto_now=True, verbose_name='Yaranma tarixi')),
                ('blog_slug', models.SlugField(editable=False, unique=True)),
                ('yayinda_mi', models.BooleanField(default=False, verbose_name='Yayına buraxılsın?')),
                ('yeni_mi', models.BooleanField(default=True, verbose_name='Yeni məqalə?')),
                ('karuselde', models.BooleanField(default=False, verbose_name='Karuseldə')),
            ],
            options={
                'verbose_name': 'Məqalə',
                'verbose_name_plural': 'Məqalələr',
            },
        ),
        migrations.CreateModel(
            name='Kateqoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kateqoriya_adi', models.CharField(max_length=150, verbose_name='Kateqoriya adı')),
                ('kateqoriya_slug', models.SlugField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
    ]
