# Generated by Django 4.2.8 on 2024-01-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kateqoriya_adi', models.CharField(max_length=150, verbose_name='kateqoriyanın adı')),
                ('kateqoriya_slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='deyisdirilme_tarixi',
            field=models.DateTimeField(auto_now=True, verbose_name='Yaranma tarixi'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='yaradilma_tarixi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi'),
        ),
    ]
