# Generated by Django 4.2.8 on 2024-01-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_kateqoriya',
            field=models.ManyToManyField(to='blog.kateqoriya', verbose_name='Kateqoriyaları seçin.'),
        ),
    ]
