# Generated by Django 4.2.8 on 2024-01-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_kateqoriya'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='basliq_sekli',
            field=models.ImageField(default='uploads/default.png', upload_to='uploads/%d%m%Y'),
        ),
    ]
