# Generated by Django 4.2.8 on 2024-01-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_basliq_sekli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='basliq_sekli',
            field=models.ImageField(blank=True, default='uploads/default.png', null=True, upload_to='uploads/%d%m%Y'),
        ),
    ]
