# Generated by Django 4.2.8 on 2024-01-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_basliq_sekli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='basliq_sekli',
            field=models.ImageField(blank=True, default='uploads/default.jpg', null=True, upload_to='uploads/%d.%m.%Y'),
        ),
    ]
