# Generated by Django 4.2.8 on 2024-01-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Müəllif', 'verbose_name_plural': 'Müəlliflər'},
        ),
    ]
