# Generated by Django 4.2.8 on 2024-01-26 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_author_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
