# Generated by Django 4.2.8 on 2024-01-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_author_author_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
